name: Build From Development

on:
  workflow_dispatch:
  push:
    branches: [ "Development" ]

jobs:
  DevBuild:
    name: Build From Development Branch
    runs-on: ubuntu-latest

    steps:
      - name: Check Path
        run: echo ${{ github.workspace }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: Development

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Run Makefile to compile program
        run: make project=Cataphract all 2>&1 | tee CompileLogs/Compile.log

      - name: Upload the Build Artefacts
        uses: actions/upload-artifact@v4
        with:
          name: Cataphract
          path: ${{ github.workspace }}/Binaries/
